/**
 * Canonical-proof comparison for the strict step-by-step verifier.
 * `matchesCanonicalProof` regenerates the proof a prover writes for one proof
 * cycle and compares it, byte for byte, with the proof it was given.
 *
 * The layout is BatchAVLProver.generateProof()'s: the cycle's old tree packed
 * post-order, END_OF_TREE, then the direction bits.
 *
 * See AVLTREE_INTERFACE → The strict verifier.
 */

import { label, type AvlNode } from '@ergots/avltree'

// The packed-proof tokens: LEAF_IN_PACKAGED_PROOF, LABEL_IN_PACKAGED_PROOF
// and END_OF_TREE_IN_PACKAGED_PROOF. @ergots/avltree's prover and decoder
// each define them; these local names stop the bundler from renumbering
// those identifiers in dist/index.js.
const PACKED_LEAF = 0x02
const PACKED_LABEL = 0x03
const PACKED_END_OF_TREE = 0x04

/**
 * Whether `proof` is exactly the proof a prover writes for a cycle whose old
 * tree is `oldRoot`, whose visited nodes are `visited`, and whose directions
 * are the bits of `proof` from `directionsStartBit` up to `directionsEndBit`.
 *
 * - `visited` is read, never written: the caller's set keeps growing as it
 *   performs operations.
 * - `directionsStartBit` is the bit after END_OF_TREE, a multiple of 8.
 *   `directionsEndBit` is the caller's cursor. It only advances, so it is
 *   never below `directionsStartBit`.
 * - Returns false at the first byte that differs.
 * - Throws a plain Error on either of two caller inconsistencies. Neither is
 *   a verdict on the proof:
 *   - `directionsEndBit` is below `directionsStartBit`;
 *   - `visited` holds a label stub. The engine fails the operation at every
 *     site that can meet a stub.
 *
 * It hashes nothing when `oldRoot` came from proof decoding: the decode-time
 * digest check has already cached every node's label.
 */
export function matchesCanonicalProof(
  proof: Uint8Array,
  oldRoot: AvlNode,
  visited: ReadonlySet<AvlNode>,
  valueLengthOpt: number | null,
  directionsStartBit: number,
  directionsEndBit: number,
): boolean {
  // Without this, a negative bit count would reach the directions check
  // below, which could then answer true.
  if (directionsEndBit < directionsStartBit) {
    throw new Error(
      'matchesCanonicalProof: the directions end before they start — the caller passed an inconsistent cursor',
    )
  }

  // Cursor into `proof`: the regenerated bytes are compared as they are produced.
  let at = 0
  const byteIs = (b: number): boolean => {
    if (proof[at] !== b) return false
    at += 1
    return true
  }
  const bytesAre = (bs: Uint8Array): boolean => {
    if (at + bs.length > proof.length) return false
    for (let j = 0; j < bs.length; j += 1) {
      if (proof[at + j] !== bs[j]) return false
    }
    at += bs.length
    return true
  }

  // 1. The packed tree, post-order. An explicit stack, so the walk costs no
  //    native frame per level. An entry is a node still to write, or the
  //    balance byte of a visited internal node whose two subtrees have been
  //    scheduled ahead of it.
  let previousLeafAvailable = false
  const stack: Array<AvlNode | number> = [oldRoot]
  while (stack.length > 0) {
    const entry = stack.pop()!
    if (typeof entry === 'number') {
      // The balance byte. It does not reset key chaining.
      if (!byteIs(entry)) return false
      continue
    }
    const node = entry
    if (!visited.has(node)) {
      // Unvisited: a label, and the subtree is not descended.
      if (!byteIs(PACKED_LABEL)) return false
      if (!bytesAre(label(node))) return false
      previousLeafAvailable = false
      continue
    }
    if (node.kind === 'leaf') {
      // A visited leaf. Its key is omitted when the previous token was a
      // leaf: the decoder takes it from that leaf's nextLeafKey.
      if (!byteIs(PACKED_LEAF)) return false
      if (!previousLeafAvailable && !bytesAre(node.key)) return false
      if (!bytesAre(node.nextLeafKey)) return false
      if (valueLengthOpt === null) {
        const n = node.value.length
        if (
          !byteIs((n >>> 24) & 0xff) ||
          !byteIs((n >>> 16) & 0xff) ||
          !byteIs((n >>> 8) & 0xff) ||
          !byteIs(n & 0xff)
        ) {
          return false
        }
      }
      if (!bytesAre(node.value)) return false
      previousLeafAvailable = true
      continue
    }
    if (node.kind === 'internal') {
      // A visited internal node: left subtree, right subtree, then its balance.
      stack.push(node.balance & 0xff, node.right, node.left)
      continue
    }
    throw new Error(
      'matchesCanonicalProof: a label stub is in the visited set — the shared engine is in an inconsistent state',
    )
  }

  // 2. END_OF_TREE, which must end where the decoder found it.
  if (!byteIs(PACKED_END_OF_TREE)) return false
  if (at * 8 !== directionsStartBit) return false

  // 3. The directions. The regenerated directions are the bits the replay
  //    read, packed LSB-first with zero padding. Those bits are the proof's
  //    own, so only the region's length and its padding can differ.
  const bits = directionsEndBit - directionsStartBit
  if (proof.length !== at + ((bits + 7) >> 3)) return false
  const usedInLastByte = bits & 7
  if (usedInLastByte !== 0 && (proof[proof.length - 1]! >>> usedInLastByte) !== 0) return false
  return true
}
