import { describe, it, expect } from 'vitest';
import {
  buildPost,
  buildLike,
  buildVouch,
  buildUnvouch,
  buildInvite,
  buildWithdraw,
  txToJson,
  InsufficientKarma,
  type BuildContext,
} from '../src/wallet/builders';
import { VOUCH_KARMA_AMOUNT, type UtxoTransaction } from '@dagsocial/types';

// The builders produce the box shapes validateTx demands, encoded through
// @dagsocial/types. They are pinned to a SECOND implementation — the demo UI's
// buildPostTx / buildLikeTx — rather than to themselves: the txIds below were
// generated by lifting those declarations out of packages/node/public/index.html
// and running computeTxId over them exactly as ui-crypto-mirror.test.ts does, at
// height 5000, era 1, one spendable box of 227 (boxId 'cc'*32), author 'aa'*32,
// a reply parent 'bb'*32 / 'dd'*32 and a like target 'bb'*32 / 'ee'*32, over the
// content strings named here. A disagreement is a finding, not a value to adjust.

const PUB = 'aa'.repeat(32);
const PARENT_AUTHOR = 'bb'.repeat(32);
const BOX_ID = 'cc'.repeat(32);
const PARENT_ID = 'dd'.repeat(32);
const TARGET_ID = 'ee'.repeat(32);
const THREAD_CONTENT = 'a test thread ✓';
const REPLY_CONTENT = 'a test reply ✓';

const THREAD_TXID = 'b01650fb9d56400431bcc95602ff05d9cd0863b4ea9ace6423bdb2f3df55b9b1';
const THREAD_CHANGE = 'f84a0f09fecb361d81619f12d0c5a0b008e594c48dc68ee0a0b5b287a0a7256e';
const REPLY_TXID = 'c7d91980fd0b29a910b713b80b0b61d3ae269ab9cd0c6011eab9362418fa2fbe';
const REPLY_CHANGE = 'a9cd35ae743223e7ce731b38cf6ea52042eccb2a8262fdc04f53d864eda91457';
const LIKE_TXID = '1506de0492fe03e091c80f5347296be86a0f08e4bc44bd902995036732c5c3f3';
const LIKE_CHANGE = 'abc49c9370884b362ecad4cc7f043695d46168abbfefce75b2006e245994760d';
const THREAD_CONTENT_HASH = '8bc41f00d29d7adc055bc479bf21e13473a34426470b92aa675c6f83eba2429f';

// The membership vectors, generated the same way — the demo UI's buildVouchTx /
// buildCreateInviteTx / buildUnvouchTx lifted by name from
// packages/node/public/index.html and run through computeTxId at height 5000,
// era 1, one spendable box of 227 ('cc'*32), author 'aa'*32, over a vouch target
// '11'*32, an invitee '22'*32 with a bond of 100, and an unvouch of a vouch box
// '33'*32 (stake 1, cast at 4990, cooldown 60 → release 5050).
const VOUCH_TARGET = '11'.repeat(32);
const INVITEE = '22'.repeat(32);
const VOUCH_BOX = '33'.repeat(32);
const VOUCH_TXID = '8afa40f04ad8c2cd8eda42cad01495f9d448a300fe4a9b0ecd086f59a0391758';
const VOUCH_CHANGE = 'b82df0bdb2085761f378baefc7f42eca94392826a64952a507958b5151eb7b65';
const INVITE_TXID = '42226c9cc552a97def81788fcd01c8afacb9a5a9d90551afca8ce1f052a07d84';
const INVITE_CHANGE = '7971f96c1ef879c5e200c60f4089be5ba8de0a5f354800d71a245cce2ea9c27d';
const UNVOUCH_TXID = '5ed21bb1fedca5f69b55c38702028f91eccb3cc44f3e9938af3ab28ffb39ab85';

// The withdraw vector, generated the same way — the demo UI's
// buildPostWithdrawTx lifted by name from packages/node/public/index.html and run
// through computeTxId / computeCandidateBoxId at height 5000, era 1, one spendable
// box of 227 ('cc'*32), author 'aa'*32, over a post id 'ff'*32.
const WITHDRAW_POST_ID = 'ff'.repeat(32);
const WITHDRAW_TXID = '2fe448f1d62f1ba4cff6ac77f4b7aeacc07752bd4876309dd82f17ee32df1a9c';
const WITHDRAW_OUTPUT = '4d2284cc4792e0aaa8ac6bc5daedf52d43636b127eab7e5a2ff922a88cc8de9f';

function hexToBytes(hex: string): Uint8Array {
  const out = new Uint8Array(hex.length / 2);
  for (let i = 0; i < out.length; i++) out[i] = parseInt(hex.slice(i * 2, i * 2 + 2), 16);
  return out;
}
function toHex(bytes: Uint8Array): string {
  let s = '';
  for (const b of bytes) s += b.toString(16).padStart(2, '0');
  return s;
}

const ctx = (): BuildContext => ({ spendable: [{ boxId: BOX_ID, value: 227n }], height: 5000, era: 1, author: PUB });

describe('builders — frozen against the demo UI vectors', () => {
  it('a root post matches the demo UI txId and change box, and pays POST_PRICE_THREAD', () => {
    const built = buildPost(ctx(), THREAD_CONTENT);
    expect(built.txId).toBe(THREAD_TXID);
    expect(built.change).toEqual({ boxId: THREAD_CHANGE, value: 222n, createdAtBlock: 5000 });
    expect(built.tx.inputs).toEqual([BOX_ID]);
    expect(built.tx.outputs).toEqual([
      { boxType: 'karma', value: 222n, createdAtBlock: 5000, owner: hexToBytes(PUB) },
      { boxType: 'karma_price', value: 5n, createdAtBlock: 5000 },
    ]);
    expect(built.tx.post?.parentRefs).toEqual([]);
    expect(toHex(built.tx.post!.contentHash)).toBe(THREAD_CONTENT_HASH);
    expect(built.tx.likeTarget).toBeUndefined();
    // Conservation: the change plus the price equals the one selected box.
    expect(built.change!.value + 5n).toBe(227n);
  });

  it('a reply matches the demo UI txId and addresses the share to the confirmed author', () => {
    const built = buildPost(ctx(), REPLY_CONTENT, { id: PARENT_ID, authorHex: PARENT_AUTHOR });
    expect(built.txId).toBe(REPLY_TXID);
    expect(built.change).toEqual({ boxId: REPLY_CHANGE, value: 224n, createdAtBlock: 5000 });
    expect(built.tx.outputs).toEqual([
      { boxType: 'karma', value: 224n, createdAtBlock: 5000, owner: hexToBytes(PUB) },
      { boxType: 'karma_price', value: 2n, createdAtBlock: 5000 },
      { boxType: 'like_accrual', value: 1n, createdAtBlock: 5000, author: hexToBytes(PARENT_AUTHOR) },
    ]);
    expect(built.tx.post?.parentRefs).toEqual([PARENT_ID]);
    // Conservation: 224 + (2 + 1) = 227.
    expect(built.change!.value + 2n + 1n).toBe(227n);
  });

  it('a like matches the demo UI txId, sets likeTarget, and carries no post', () => {
    const built = buildLike(ctx(), TARGET_ID, PARENT_AUTHOR);
    expect(built.txId).toBe(LIKE_TXID);
    expect(built.change).toEqual({ boxId: LIKE_CHANGE, value: 226n, createdAtBlock: 5000 });
    expect(built.tx.outputs).toEqual([
      { boxType: 'karma', value: 226n, createdAtBlock: 5000, owner: hexToBytes(PUB) },
      { boxType: 'like_accrual', value: 1n, createdAtBlock: 5000, author: hexToBytes(PARENT_AUTHOR) },
    ]);
    expect(built.tx.likeTarget).toBe(TARGET_ID);
    expect(built.tx.post).toBeUndefined();
  });
});

describe('builders — structural rules', () => {
  it('a zero change is no box', () => {
    // Exactly the thread price: no karma change output.
    const thread = buildPost({ ...ctx(), spendable: [{ boxId: BOX_ID, value: 5n }] }, 'x');
    expect(thread.change).toBeNull();
    expect(thread.tx.outputs).toEqual([{ boxType: 'karma_price', value: 5n, createdAtBlock: 5000 }]);
    // Exactly the reply price: still the share and the pool, no change.
    const reply = buildPost({ ...ctx(), spendable: [{ boxId: BOX_ID, value: 3n }] }, 'x', { id: PARENT_ID, authorHex: PARENT_AUTHOR });
    expect(reply.change).toBeNull();
    expect(reply.tx.outputs.map((o) => o.boxType)).toEqual(['karma_price', 'like_accrual']);
  });

  it('InsufficientKarma when the spendable view cannot cover the price', () => {
    expect(() => buildPost({ ...ctx(), spendable: [{ boxId: BOX_ID, value: 4n }] }, 'x')).toThrow(InsufficientKarma);
    try {
      buildPost({ ...ctx(), spendable: [{ boxId: BOX_ID, value: 4n }] }, 'x');
    } catch (e) {
      expect(e).toBeInstanceOf(InsufficientKarma);
      expect((e as InsufficientKarma).required).toBe(5n);
      expect((e as InsufficientKarma).available).toBe(4n);
    }
    expect(() => buildLike({ ...ctx(), spendable: [] }, TARGET_ID, PARENT_AUTHOR)).toThrow(InsufficientKarma);
  });

  it('selection sorts value-descending before selectBoxes', () => {
    const spendable = [
      { boxId: 'a'.repeat(64), value: 3n },
      { boxId: 'b'.repeat(64), value: 10n },
      { boxId: 'c'.repeat(64), value: 1n },
    ];
    // Price 5 is covered by the single largest box; the others are untouched.
    const built = buildPost({ ...ctx(), spendable }, 'x');
    expect(built.tx.inputs).toEqual(['b'.repeat(64)]);
    expect(built.change!.value).toBe(5n);
  });
});

describe('membership builders — frozen against the demo UI vectors', () => {
  it('a vouch matches the demo UI txId and change box, and stakes exactly VOUCH_KARMA_AMOUNT', () => {
    const built = buildVouch(ctx(), VOUCH_TARGET);
    expect(built.txId).toBe(VOUCH_TXID);
    expect(built.change).toEqual({ boxId: VOUCH_CHANGE, value: 226n, createdAtBlock: 5000 });
    expect(built.tx.inputs).toEqual([BOX_ID]);
    expect(built.tx.outputs).toEqual([
      { boxType: 'karma', value: 226n, createdAtBlock: 5000, owner: hexToBytes(PUB) },
      { boxType: 'vouch', value: VOUCH_KARMA_AMOUNT, createdAtBlock: 5000, voucherId: hexToBytes(PUB), targetId: hexToBytes(VOUCH_TARGET) },
    ]);
    expect((built.tx.outputs[1] as { value: bigint }).value).toBe(VOUCH_KARMA_AMOUNT);
    expect(built.tx.post).toBeUndefined();
    expect(built.tx.likeTarget).toBeUndefined();
    // Conservation: the change plus the stake equals the one selected box.
    expect(built.change!.value + VOUCH_KARMA_AMOUNT).toBe(227n);
  });

  it('an unvouch matches: one input, one escrow of the box value, release = cast + cooldown, no karma', () => {
    const built = buildUnvouch(ctx(), { boxId: VOUCH_BOX, value: 1n, createdAtBlock: 4990 }, 60);
    expect(built.txId).toBe(UNVOUCH_TXID);
    expect(built.change).toBeNull();
    expect(built.tx.inputs).toEqual([VOUCH_BOX]);
    expect(built.tx.outputs).toEqual([
      { boxType: 'vouch_escrow', value: 1n, createdAtBlock: 5000, owner: hexToBytes(PUB), releaseAtBlock: 5050 },
    ]);
    // No karma output — the stake is held, not returned as change.
    expect(built.tx.outputs.every((o) => o.boxType !== 'karma')).toBe(true);
  });

  it('an invite matches the demo UI txId and carries the bond named', () => {
    const built = buildInvite(ctx(), INVITEE, 100n);
    expect(built.txId).toBe(INVITE_TXID);
    expect(built.change).toEqual({ boxId: INVITE_CHANGE, value: 127n, createdAtBlock: 5000 });
    expect(built.tx.outputs).toEqual([
      { boxType: 'karma', value: 127n, createdAtBlock: 5000, owner: hexToBytes(PUB) },
      { boxType: 'bond', value: 100n, createdAtBlock: 5000, inviterId: hexToBytes(PUB), inviteePublicKey: hexToBytes(INVITEE) },
    ]);
    // Conservation: 127 + 100 = 227.
    expect(built.change!.value + 100n).toBe(227n);
  });
});

describe('membership builders — structural rules', () => {
  it('a vouch from a single 1-karma box emits no change', () => {
    const built = buildVouch({ ...ctx(), spendable: [{ boxId: BOX_ID, value: 1n }] }, VOUCH_TARGET);
    expect(built.change).toBeNull();
    expect(built.tx.outputs).toEqual([
      { boxType: 'vouch', value: VOUCH_KARMA_AMOUNT, createdAtBlock: 5000, voucherId: hexToBytes(PUB), targetId: hexToBytes(VOUCH_TARGET) },
    ]);
  });

  it('InsufficientKarma names the bond when the view cannot cover it', () => {
    expect(() => buildInvite({ ...ctx(), spendable: [{ boxId: BOX_ID, value: 50n }] }, INVITEE, 100n)).toThrow(InsufficientKarma);
    try {
      buildInvite({ ...ctx(), spendable: [{ boxId: BOX_ID, value: 50n }] }, INVITEE, 100n);
    } catch (e) {
      expect(e).toBeInstanceOf(InsufficientKarma);
      expect((e as InsufficientKarma).required).toBe(100n);
      expect((e as InsufficientKarma).available).toBe(50n);
    }
    // A vouch is unaffordable below VOUCH_KARMA_AMOUNT.
    expect(() => buildVouch({ ...ctx(), spendable: [] }, VOUCH_TARGET)).toThrow(InsufficientKarma);
  });
});

describe('withdraw builder — frozen against the demo UI vector', () => {
  it('a withdrawal matches the demo UI txId and output id, spends and returns one karma box', () => {
    const built = buildWithdraw(ctx(), WITHDRAW_POST_ID);
    expect(built.txId).toBe(WITHDRAW_TXID);
    expect(built.change).toEqual({ boxId: WITHDRAW_OUTPUT, value: 227n, createdAtBlock: 5000 });
    expect(built.tx.inputs).toEqual([BOX_ID]);
    expect(built.tx.outputs).toEqual([
      { boxType: 'karma', value: 227n, createdAtBlock: 5000, owner: hexToBytes(PUB) },
    ]);
    expect(built.tx.postWithdraw).toEqual({ postId: WITHDRAW_POST_ID });
    expect(built.tx.post).toBeUndefined();
    expect(built.tx.likeTarget).toBeUndefined();
    // Conservation: one box in, its whole value back out.
    expect(built.change!.value).toBe(227n);
  });
});

describe('withdraw builder — structural rules', () => {
  it('spends the smallest box when the view holds several', () => {
    const spendable = [
      { boxId: 'a'.repeat(64), value: 10n },
      { boxId: 'b'.repeat(64), value: 3n },
      { boxId: 'c'.repeat(64), value: 7n },
    ];
    const built = buildWithdraw({ ...ctx(), spendable }, WITHDRAW_POST_ID);
    expect(built.tx.inputs).toEqual(['b'.repeat(64)]);
    expect(built.change!.value).toBe(3n);
    expect(built.tx.outputs).toEqual([
      { boxType: 'karma', value: 3n, createdAtBlock: 5000, owner: hexToBytes(PUB) },
    ]);
  });

  it('InsufficientKarma names one box when the spendable view is empty', () => {
    expect(() => buildWithdraw({ ...ctx(), spendable: [] }, WITHDRAW_POST_ID)).toThrow(InsufficientKarma);
    try {
      buildWithdraw({ ...ctx(), spendable: [] }, WITHDRAW_POST_ID);
    } catch (e) {
      expect(e).toBeInstanceOf(InsufficientKarma);
      expect((e as InsufficientKarma).required).toBe(1n);
      expect((e as InsufficientKarma).available).toBe(0n);
    }
  });
});

describe('txToJson — the node JSON edge', () => {
  const sign = (tx: UtxoTransaction): UtxoTransaction => ({ ...tx, signatures: { [PUB]: new Uint8Array(64) } });

  it('renders a post: hex owner/author, decimal-string values, the commit, one signature', () => {
    const built = buildPost(ctx(), THREAD_CONTENT);
    const body = txToJson(sign(built.tx));
    expect(body.inputs).toEqual([BOX_ID]);
    expect(body.outputs).toEqual([
      { boxType: 'karma', value: '222', createdAtBlock: 5000, owner: PUB },
      { boxType: 'karma_price', value: '5', createdAtBlock: 5000 },
    ]);
    expect(body.post).toEqual({
      contentHash: THREAD_CONTENT_HASH,
      author: PUB,
      parentRefs: [],
      protocolVersion: 1,
      type: 'regular',
    });
    expect(body.signatures).toEqual({ [PUB]: '00'.repeat(64) });
    expect(body.likeTarget).toBeUndefined();
  });

  it('renders a like: likeTarget present, no post, exactly one signature', () => {
    const built = buildLike(ctx(), TARGET_ID, PARENT_AUTHOR);
    const body = txToJson(sign(built.tx));
    expect(body.likeTarget).toBe(TARGET_ID);
    expect(body.post).toBeUndefined();
    expect(Object.keys(body.signatures as object)).toHaveLength(1);
    expect(body.outputs).toEqual([
      { boxType: 'karma', value: '226', createdAtBlock: 5000, owner: PUB },
      { boxType: 'like_accrual', value: '1', createdAtBlock: 5000, author: PARENT_AUTHOR },
    ]);
  });

  it('renders a vouch: hex voucherId/targetId, decimal value', () => {
    const built = buildVouch(ctx(), VOUCH_TARGET);
    const body = txToJson(sign(built.tx));
    expect(body.outputs).toEqual([
      { boxType: 'karma', value: '226', createdAtBlock: 5000, owner: PUB },
      { boxType: 'vouch', value: '1', createdAtBlock: 5000, voucherId: PUB, targetId: VOUCH_TARGET },
    ]);
    expect(body.post).toBeUndefined();
    expect(body.likeTarget).toBeUndefined();
  });

  it('renders an unvouch: escrow owner hex, decimal value, releaseAtBlock a number', () => {
    const built = buildUnvouch(ctx(), { boxId: VOUCH_BOX, value: 1n, createdAtBlock: 4990 }, 60);
    const body = txToJson(sign(built.tx));
    expect(body.inputs).toEqual([VOUCH_BOX]);
    expect(body.outputs).toEqual([
      { boxType: 'vouch_escrow', value: '1', createdAtBlock: 5000, owner: PUB, releaseAtBlock: 5050 },
    ]);
  });

  it('renders an invite: hex inviterId/inviteePublicKey, decimal value', () => {
    const built = buildInvite(ctx(), INVITEE, 100n);
    const body = txToJson(sign(built.tx));
    expect(body.outputs).toEqual([
      { boxType: 'karma', value: '127', createdAtBlock: 5000, owner: PUB },
      { boxType: 'bond', value: '100', createdAtBlock: 5000, inviterId: PUB, inviteePublicKey: INVITEE },
    ]);
  });

  it('renders a withdrawal: postWithdraw present, one karma output, no post/likeTarget', () => {
    const built = buildWithdraw(ctx(), WITHDRAW_POST_ID);
    const body = txToJson(sign(built.tx));
    expect(body.inputs).toEqual([BOX_ID]);
    expect(body.outputs).toEqual([
      { boxType: 'karma', value: '227', createdAtBlock: 5000, owner: PUB },
    ]);
    expect(body.postWithdraw).toEqual({ postId: WITHDRAW_POST_ID });
    expect(body.post).toBeUndefined();
    expect(body.likeTarget).toBeUndefined();
  });
});
