import { describe, it, expect } from 'vitest';
import { buildPost, buildLike, txToJson, InsufficientKarma, type BuildContext } from '../src/wallet/builders';
import type { UtxoTransaction } from '@dagsocial/types';

// The builders produce the box shapes validateTx demands, encoded through
// @dagsocial/types. They are pinned to a SECOND implementation — the demo UI's
// buildPostTx / buildLikeTx — rather than to themselves: the txIds below were
// generated by lifting those declarations out of packages/node/public/index.html
// and running computeTxId over them exactly as ui-crypto-mirror.test.ts does, at
// height 5000, era 1, one spendable box of 227 (boxId 'cc'*32), author 'aa'*32,
// a reply parent 'bb'*32 / 'dd'*32 and a like target 'bb'*32 / 'ee'*32, over the
// content strings named here. A disagreement is a finding, not a value to adjust.

const PUB = 'aa'.repeat(32);
const PARENT_AUTHOR = 'bb'.repeat(32);
const BOX_ID = 'cc'.repeat(32);
const PARENT_ID = 'dd'.repeat(32);
const TARGET_ID = 'ee'.repeat(32);
const THREAD_CONTENT = 'a test thread ✓';
const REPLY_CONTENT = 'a test reply ✓';

const THREAD_TXID = 'b01650fb9d56400431bcc95602ff05d9cd0863b4ea9ace6423bdb2f3df55b9b1';
const THREAD_CHANGE = 'f84a0f09fecb361d81619f12d0c5a0b008e594c48dc68ee0a0b5b287a0a7256e';
const REPLY_TXID = 'c7d91980fd0b29a910b713b80b0b61d3ae269ab9cd0c6011eab9362418fa2fbe';
const REPLY_CHANGE = 'a9cd35ae743223e7ce731b38cf6ea52042eccb2a8262fdc04f53d864eda91457';
const LIKE_TXID = '1506de0492fe03e091c80f5347296be86a0f08e4bc44bd902995036732c5c3f3';
const LIKE_CHANGE = 'abc49c9370884b362ecad4cc7f043695d46168abbfefce75b2006e245994760d';
const THREAD_CONTENT_HASH = '8bc41f00d29d7adc055bc479bf21e13473a34426470b92aa675c6f83eba2429f';

function hexToBytes(hex: string): Uint8Array {
  const out = new Uint8Array(hex.length / 2);
  for (let i = 0; i < out.length; i++) out[i] = parseInt(hex.slice(i * 2, i * 2 + 2), 16);
  return out;
}
function toHex(bytes: Uint8Array): string {
  let s = '';
  for (const b of bytes) s += b.toString(16).padStart(2, '0');
  return s;
}

const ctx = (): BuildContext => ({ spendable: [{ boxId: BOX_ID, value: 227n }], height: 5000, era: 1, author: PUB });

describe('builders — frozen against the demo UI vectors', () => {
  it('a root post matches the demo UI txId and change box, and pays POST_PRICE_THREAD', () => {
    const built = buildPost(ctx(), THREAD_CONTENT);
    expect(built.txId).toBe(THREAD_TXID);
    expect(built.change).toEqual({ boxId: THREAD_CHANGE, value: 222n, createdAtBlock: 5000 });
    expect(built.tx.inputs).toEqual([BOX_ID]);
    expect(built.tx.outputs).toEqual([
      { boxType: 'karma', value: 222n, createdAtBlock: 5000, owner: hexToBytes(PUB) },
      { boxType: 'karma_price', value: 5n, createdAtBlock: 5000 },
    ]);
    expect(built.tx.post?.parentRefs).toEqual([]);
    expect(toHex(built.tx.post!.contentHash)).toBe(THREAD_CONTENT_HASH);
    expect(built.tx.likeTarget).toBeUndefined();
    // Conservation: the change plus the price equals the one selected box.
    expect(built.change!.value + 5n).toBe(227n);
  });

  it('a reply matches the demo UI txId and addresses the share to the confirmed author', () => {
    const built = buildPost(ctx(), REPLY_CONTENT, { id: PARENT_ID, authorHex: PARENT_AUTHOR });
    expect(built.txId).toBe(REPLY_TXID);
    expect(built.change).toEqual({ boxId: REPLY_CHANGE, value: 224n, createdAtBlock: 5000 });
    expect(built.tx.outputs).toEqual([
      { boxType: 'karma', value: 224n, createdAtBlock: 5000, owner: hexToBytes(PUB) },
      { boxType: 'karma_price', value: 2n, createdAtBlock: 5000 },
      { boxType: 'like_accrual', value: 1n, createdAtBlock: 5000, author: hexToBytes(PARENT_AUTHOR) },
    ]);
    expect(built.tx.post?.parentRefs).toEqual([PARENT_ID]);
    // Conservation: 224 + (2 + 1) = 227.
    expect(built.change!.value + 2n + 1n).toBe(227n);
  });

  it('a like matches the demo UI txId, sets likeTarget, and carries no post', () => {
    const built = buildLike(ctx(), TARGET_ID, PARENT_AUTHOR);
    expect(built.txId).toBe(LIKE_TXID);
    expect(built.change).toEqual({ boxId: LIKE_CHANGE, value: 226n, createdAtBlock: 5000 });
    expect(built.tx.outputs).toEqual([
      { boxType: 'karma', value: 226n, createdAtBlock: 5000, owner: hexToBytes(PUB) },
      { boxType: 'like_accrual', value: 1n, createdAtBlock: 5000, author: hexToBytes(PARENT_AUTHOR) },
    ]);
    expect(built.tx.likeTarget).toBe(TARGET_ID);
    expect(built.tx.post).toBeUndefined();
  });
});

describe('builders — structural rules', () => {
  it('a zero change is no box', () => {
    // Exactly the thread price: no karma change output.
    const thread = buildPost({ ...ctx(), spendable: [{ boxId: BOX_ID, value: 5n }] }, 'x');
    expect(thread.change).toBeNull();
    expect(thread.tx.outputs).toEqual([{ boxType: 'karma_price', value: 5n, createdAtBlock: 5000 }]);
    // Exactly the reply price: still the share and the pool, no change.
    const reply = buildPost({ ...ctx(), spendable: [{ boxId: BOX_ID, value: 3n }] }, 'x', { id: PARENT_ID, authorHex: PARENT_AUTHOR });
    expect(reply.change).toBeNull();
    expect(reply.tx.outputs.map((o) => o.boxType)).toEqual(['karma_price', 'like_accrual']);
  });

  it('InsufficientKarma when the spendable view cannot cover the price', () => {
    expect(() => buildPost({ ...ctx(), spendable: [{ boxId: BOX_ID, value: 4n }] }, 'x')).toThrow(InsufficientKarma);
    try {
      buildPost({ ...ctx(), spendable: [{ boxId: BOX_ID, value: 4n }] }, 'x');
    } catch (e) {
      expect(e).toBeInstanceOf(InsufficientKarma);
      expect((e as InsufficientKarma).required).toBe(5n);
      expect((e as InsufficientKarma).available).toBe(4n);
    }
    expect(() => buildLike({ ...ctx(), spendable: [] }, TARGET_ID, PARENT_AUTHOR)).toThrow(InsufficientKarma);
  });

  it('selection sorts value-descending before selectBoxes', () => {
    const spendable = [
      { boxId: 'a'.repeat(64), value: 3n },
      { boxId: 'b'.repeat(64), value: 10n },
      { boxId: 'c'.repeat(64), value: 1n },
    ];
    // Price 5 is covered by the single largest box; the others are untouched.
    const built = buildPost({ ...ctx(), spendable }, 'x');
    expect(built.tx.inputs).toEqual(['b'.repeat(64)]);
    expect(built.change!.value).toBe(5n);
  });
});

describe('txToJson — the node JSON edge', () => {
  const sign = (tx: UtxoTransaction): UtxoTransaction => ({ ...tx, signatures: { [PUB]: new Uint8Array(64) } });

  it('renders a post: hex owner/author, decimal-string values, the commit, one signature', () => {
    const built = buildPost(ctx(), THREAD_CONTENT);
    const body = txToJson(sign(built.tx));
    expect(body.inputs).toEqual([BOX_ID]);
    expect(body.outputs).toEqual([
      { boxType: 'karma', value: '222', createdAtBlock: 5000, owner: PUB },
      { boxType: 'karma_price', value: '5', createdAtBlock: 5000 },
    ]);
    expect(body.post).toEqual({
      contentHash: THREAD_CONTENT_HASH,
      author: PUB,
      parentRefs: [],
      protocolVersion: 1,
      type: 'regular',
    });
    expect(body.signatures).toEqual({ [PUB]: '00'.repeat(64) });
    expect(body.likeTarget).toBeUndefined();
  });

  it('renders a like: likeTarget present, no post, exactly one signature', () => {
    const built = buildLike(ctx(), TARGET_ID, PARENT_AUTHOR);
    const body = txToJson(sign(built.tx));
    expect(body.likeTarget).toBe(TARGET_ID);
    expect(body.post).toBeUndefined();
    expect(Object.keys(body.signatures as object)).toHaveLength(1);
    expect(body.outputs).toEqual([
      { boxType: 'karma', value: '226', createdAtBlock: 5000, owner: PUB },
      { boxType: 'like_accrual', value: '1', createdAtBlock: 5000, author: PARENT_AUTHOR },
    ]);
  });
});
