import { readFileSync } from 'node:fs';
import { describe, it, expect } from 'vitest';
import type { SubBlockTree, UtxoTxTree, CoinbaseOutput, SubBlockEntry } from '@dagsocial/types';
import { buildMerkleRoot, leafHash, hexToBuf } from '@dagsocial/types';
import {
  computeSubBlockRoot,
  computeUtxoTxRoot,
} from '../../src/services/block-creator.js';

// ---------------------------------------------------------------------------
// Merkle root pins for the two roots node computes.
//
// ## What this file used to prove, and why that proof is retired
//
// It was the P2-D N3a/T2b root-invariance pin: the retired like-box and epoch
// arms, and later the retired UtxoTxTree fields, were never leaves, so deleting
// them had to move zero root bytes. That was a point-in-time two-sided pin — it
// ran green against the pre-deletion code, then green again after — and its
// evidentiary value was spent the moment both sides ran. What survived was a
// plain pin on two constants.
//
// Phase 4b moves both of them. The `subblock` and `coinbase` leaf preimages stop
// being `JSON.stringify` output and become the committed struct's own wire bytes
// (`subBlockEntryBytes` / `coinbaseOutputBytes` from `@dagsocial/types`). The
// `utxotx` and `prune` leaves are untouched: `utxotx` already hashed a bare
// 32-byte id and `prune` already delegated to `serializePruneEntry`.
//
// ## Where the new constants come from — NOT from running the new code
//
// A pin regenerated by pasting what the implementation emits tests nothing: it
// would hold just as firmly over a transposed layout. Both pins are therefore
// derived from preimage bytes written out by hand from the layout table
// (TYPES_INTERFACE → "Layout — Merkle leaf preimages are the struct's own wire
// bytes"), and the hand-transcription is itself checked against the byte vectors
// `@dagsocial/types` froze in `test/golden/block.json` — read from that file at
// run time, never recomputed. See the two describe blocks below.
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// The frozen vectors, read out of types' golden corpus
// ---------------------------------------------------------------------------

interface GoldenVector {
  name: string;
  value: unknown;
  bytes: string;
  note?: string;
}

const GOLDEN: GoldenVector[] = (
  JSON.parse(
    readFileSync(new URL('../../../types/test/golden/block.json', import.meta.url), 'utf8'),
  ) as { vectors: GoldenVector[] }
).vectors;

function vector(name: string): GoldenVector {
  const found = GOLDEN.find((v) => v.name === name);
  // A renamed or deleted vector must fail loudly rather than silently skip: the
  // cross-package anchor is the only thing that can see a transposed layout.
  if (!found) throw new Error(`golden vector "${name}" is gone from types/test/golden/block.json`);
  return found;
}

/** The vector's JSON `value` as a `SubBlockEntry` — all three fields are hex. */
function asSubBlockEntry(v: GoldenVector): SubBlockEntry {
  return v.value as SubBlockEntry;
}

/**
 * The vector's JSON `value` as a `CoinbaseOutput`, using the same two
 * conversions types' own harness applies: `b32bytes` is hex→`Uint8Array`,
 * `vlqU64` is a decimal string→`bigint` (JSON numbers cannot carry a u64).
 */
function asCoinbaseOutput(v: GoldenVector): CoinbaseOutput {
  const j = v.value as {
    owner: string;
    value: string;
    lockedUntilBlock: number;
    isTreasury: boolean;
  };
  return {
    owner: hexToBuf(j.owner),
    value: BigInt(j.value),
    lockedUntilBlock: j.lockedUntilBlock,
    isTreasury: j.isTreasury,
  };
}

const toHex = (b: Uint8Array): string => Buffer.from(b).toString('hex');

/** The root of a one-leaf tree is the leaf (`buildMerkleRoot`, single-leaf arm). */
const rootOfLeaves = (...preimages: [string, string][]): string =>
  toHex(buildMerkleRoot(preimages.map(([tag, bytes]) => leafHash(tag, hexToBuf(bytes)))));

// ---------------------------------------------------------------------------
// Anchor — node's leaf preimage IS types' frozen wire form
// ---------------------------------------------------------------------------
//
// This is the only check in the tree that can see a transposition of two
// same-width rows. `subBlockEntryBytes` is both the tree codec's element writer
// and the Merkle leaf preimage, so a swap of `postId` and `author` inside types
// round-trips perfectly and every encode/decode test in that package stays
// green. Only a comparison against bytes frozen on disk catches it, and only
// from this side of the package boundary does that comparison also cover the
// leaf.
// ---------------------------------------------------------------------------

describe('leaf preimages are types\' frozen wire bytes', () => {
  for (const name of ['subBlockEntry/typical', 'subBlockEntry/thread-root']) {
    it(`'subblock' leaf over ${name} matches the golden bytes`, () => {
      const v = vector(name);
      const tree: SubBlockTree = { subBlockEntries: [asSubBlockEntry(v)], pruneEntries: [] };
      expect(computeSubBlockRoot(tree)).toBe(rootOfLeaves(['subblock', v.bytes]));
    });
  }

  for (const name of ['coinbaseOutput/miner', 'coinbaseOutput/treasury']) {
    it(`'coinbase' leaf over ${name} matches the golden bytes`, () => {
      const v = vector(name);
      const tree: UtxoTxTree = {
        utxoTxIds: [],
        utxoTxs: [],
        coinbaseOutputs: [asCoinbaseOutput(v)],
      };
      expect(computeUtxoTxRoot(tree)).toBe(rootOfLeaves(['coinbase', v.bytes]));
    });
  }
});

// ---------------------------------------------------------------------------
// The pinned fixtures — unchanged values, hand-derived preimages
// ---------------------------------------------------------------------------
//
// The fixtures below are byte-for-byte the ones this file has always carried, so
// the movement pin at the bottom compares like with like. What moves is the two
// preimages, written out here by hand from the layout table:
//
//   SubBlockEntry  = b32(postId) ‖ arr(parentRefs, b32) ‖ b32(author)
//   CoinbaseOutput = b32(owner) ‖ vlqU64(value) ‖ vlqU(lockedUntilBlock) ‖ u8(isTreasury)
//
// `arr` is a vlqU count followed by the elements; vlqU/vlqU64 are base-128
// little-endian with the continuation bit set on every byte but the last.
// ---------------------------------------------------------------------------

const FIXED_OWNER = new Uint8Array(32).fill(7);

const utxoFixture: UtxoTxTree = {
  utxoTxIds: ['ab'.repeat(32), 'cd'.repeat(32)],
  utxoTxs: [], // carried bytes are not part of the root
  coinbaseOutputs: [
    {
      owner: FIXED_OWNER,
      value: 42n,
      lockedUntilBlock: 721,
      isTreasury: false,
    },
  ],
};

const subBlockFixture: SubBlockTree = {
  subBlockEntries: [
    {
      postId: 'aa'.repeat(32),
      parentRefs: ['bb'.repeat(32)],
      author: 'cc'.repeat(32),
    },
  ],
  pruneEntries: [],
};

/**
 * `b32('aa'×32)` ‖ `arr` count 1 = `01` ‖ `b32('bb'×32)` ‖ `b32('cc'×32)`.
 * Same shape as the frozen `subBlockEntry/typical`, which carries the same `01`
 * over a single ref row — `MAX_PARENT_REFS` is 1, so one ref is the typical
 * case and `subBlockEntry/thread-root` is the empty `00` one.
 */
const SUBBLOCK_LEAF_PREIMAGE = `${'aa'.repeat(32)}01${'bb'.repeat(32)}${'cc'.repeat(32)}`;

/**
 * `b32(0x07×32)` ‖ `vlqU64(42)` = `2a` ‖ `vlqU(721)` = `d105`
 * (721 = 5·128 + 81; 81|0x80 = 0xd1, then 0x05) ‖ `u8(false)` = `00`.
 */
const COINBASE_LEAF_PREIMAGE = `${'07'.repeat(32)}2ad10500`;

const PINNED_UTXO_TX_ROOT =
  '0459a94fbdd9ff7e5ae64ee45c3a1831305221466d4c1cb140f9109482040840';
const PINNED_SUB_BLOCK_ROOT =
  '805e696be152fbcc9dd2f886307ad8d1348189bae6b0f523eb2c14e8fa62b13c';

/** Both roots as this file pinned them before Phase 4b, for the movement pin. */
const PRE_4B_UTXO_TX_ROOT =
  '8ecb0e6de230bb762f65c5029572533fe55327fbf499038f9b5c98860cdce520';
const PRE_4B_SUB_BLOCK_ROOT =
  '49d3958c701a62cb6eb42293ae9852b4d21a578e92f4738bbf8dafd13d5cfe3c';

describe('Phase 4b Merkle leaf preimages', () => {
  it('subBlockRoot is the hand-derived positional preimage, hashed', () => {
    expect(computeSubBlockRoot(subBlockFixture)).toBe(
      rootOfLeaves(['subblock', SUBBLOCK_LEAF_PREIMAGE]),
    );
  });

  it('utxoTxRoot leaves are two bare ids and the hand-derived coinbase preimage', () => {
    expect(computeUtxoTxRoot(utxoFixture)).toBe(
      rootOfLeaves(
        ['utxotx', 'ab'.repeat(32)],
        ['utxotx', 'cd'.repeat(32)],
        ['coinbase', COINBASE_LEAF_PREIMAGE],
      ),
    );
  });

  it('subBlockRoot matches its pin', () => {
    expect(computeSubBlockRoot(subBlockFixture)).toBe(PINNED_SUB_BLOCK_ROOT);
  });

  it('utxoTxRoot matches its pin', () => {
    expect(computeUtxoTxRoot(utxoFixture)).toBe(PINNED_UTXO_TX_ROOT);
  });

  // Two-sided movement pin: the roots moved, and here is exactly what
  // they moved from. Every committed byte moves in this bundle, so the fresh
  // chain + wiped AVL store the standing deploy gate already mandates covers it.
  it('both roots moved off the JSON preimages', () => {
    expect(computeSubBlockRoot(subBlockFixture)).not.toBe(PRE_4B_SUB_BLOCK_ROOT);
    expect(computeUtxoTxRoot(utxoFixture)).not.toBe(PRE_4B_UTXO_TX_ROOT);
  });
});
