import { readFileSync } from 'node:fs';
import { describe, it, expect } from 'vitest';
import type { UtxoTxTree, PruneEntry } from '@dagsocial/types';
import {
  buildMerkleRoot,
  leafHash,
  hexToBuf,
  serializePruneEntry,
} from '@dagsocial/types';
import {
  computeUtxoTxRoot,
} from '../../src/services/block-creator.js';

// ---------------------------------------------------------------------------
// Merkle leaf pins for the one root node computes.
//
// ## The two leaf classes, and the two tracked holes
//
// `utxoTxRoot` has exactly two: `'utxotx'` over a bare 32-byte transaction id,
// and `'prune'` over `serializePruneEntry`. ⛔ **`'coinbase'` is a tracked
// reservation** (TYPES_INTERFACE → Tracked reservations) — a later leaf class
// wearing that tag would make historical roots ambiguous against new ones, and
// a root is the one thing that cannot be re-derived to settle the question.
//
// ## Where the pins come from — NOT from running the new code
//
// A pin regenerated by pasting what the implementation emits tests nothing: it
// would hold just as firmly over a transposed layout. The preimage below is
// written out by hand from the layout table (TYPES_INTERFACE → "Layout — Merkle
// leaf preimages are the struct's own wire bytes"), and the hand-transcription
// is itself checked against the byte vector `@dagsocial/types` froze in
// `test/golden/block.json` — read from that file at run time, never recomputed.
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// The frozen vector, read out of types' golden corpus
// ---------------------------------------------------------------------------

interface GoldenVector {
  name: string;
  value: unknown;
  bytes: string;
  note?: string;
}

const GOLDEN: GoldenVector[] = (
  JSON.parse(
    readFileSync(new URL('../../../types/test/golden/block.json', import.meta.url), 'utf8'),
  ) as { vectors: GoldenVector[] }
).vectors;

function vector(name: string): GoldenVector {
  const found = GOLDEN.find((v) => v.name === name);
  // A renamed or deleted vector must fail loudly rather than silently skip: the
  // cross-package anchor is the only thing that can see a transposed layout.
  if (!found) throw new Error(`golden vector "${name}" is gone from types/test/golden/block.json`);
  return found;
}

/**
 * The vector's `pruneEntries[0]` as a `PruneEntry`, using the conversions
 * types' own harness applies: every `b32`/`b64` field is hex→`Uint8Array`, and
 * `rootPostHash` and `subtreePostIds` stay hex strings.
 */
function asPruneEntry(v: GoldenVector): PruneEntry {
  const j = (v.value as { pruneEntries: Record<string, unknown>[] }).pruneEntries[0]!;
  return {
    rootPostHash: j.rootPostHash as string,
    subtreePostIds: j.subtreePostIds as string[],
    subtreeMerkleRoot: hexToBuf(j.subtreeMerkleRoot as string),
    authorId: hexToBuf(j.authorId as string),
    authorSignature: hexToBuf(j.authorSignature as string),
  };
}

const toHex = (b: Uint8Array): string => Buffer.from(b).toString('hex');

/** The root of a one-leaf tree is the leaf (`buildMerkleRoot`, single-leaf arm). */
const rootOfLeaves = (...preimages: [string, string][]): string =>
  toHex(buildMerkleRoot(preimages.map(([tag, bytes]) => leafHash(tag, hexToBuf(bytes)))));

// ---------------------------------------------------------------------------
// The hand-derived prune preimage
// ---------------------------------------------------------------------------
//
//   PruneEntry = b32(rootPostHash) ‖ arr(subtreePostIds, b32)
//              ‖ b32(subtreeMerkleRoot) ‖ b32(authorId) ‖ b64(authorSignature)
//
// ⚠ **Every 32-byte field carries a DIFFERENT fill**, which is the whole reason
// this catches a transposition: `rootPostHash` is `c1`, `subtreeMerkleRoot`
// `d1`, `authorId` `b1`. Same-width adjacent rows swapped inside types would
// round-trip perfectly and leave every encode/decode test in that package green.
// ---------------------------------------------------------------------------

const PRUNE_LEAF_PREIMAGE =
  'c1'.repeat(32) +   // b32(rootPostHash)
  '01' +              // arr count = 1
  'a1'.repeat(32) +   // b32(subtreePostIds[0])
  'd1'.repeat(32) +   // b32(subtreeMerkleRoot)
  'b1'.repeat(32) +   // b32(authorId)
  'e1'.repeat(64);    // b64(authorSignature)

// ---------------------------------------------------------------------------
// Anchor — node's leaf preimage IS types' frozen wire form
// ---------------------------------------------------------------------------
//
// This is the only check in the tree that can see a transposition of two
// same-width rows. `serializePruneEntry` is both the tree codec's element writer
// and the Merkle leaf preimage, so a swap inside types round-trips perfectly and
// every encode/decode test in that package stays green. Only a comparison
// against bytes frozen on disk catches it, and only from this side of the
// package boundary does that comparison also cover the leaf.
// ---------------------------------------------------------------------------

describe('leaf preimages are types\' frozen wire bytes', () => {
  // `'coinbase'` is a tracked reservation (TYPES_INTERFACE → Tracked
  // reservations). Neither it nor the free `'subblock'` has a leaf in the
  // combined tree — a post and the settlement both ride `utxoTxIds`, whose
  // leaf is a bare 32-byte id.

  const golden = vector('utxoTxTree/txs-and-prunes');

  it('the hand-transcribed prune preimage is what types encodes', () => {
    expect(toHex(serializePruneEntry(asPruneEntry(golden)))).toBe(PRUNE_LEAF_PREIMAGE);
  });

  it('and it is the tail of the frozen whole-tree bytes', () => {
    // The prune section is last in the positional layout, so the entry's own
    // bytes end the vector. A section reordered inside types moves this.
    expect(golden.bytes.endsWith(PRUNE_LEAF_PREIMAGE)).toBe(true);
  });

  it('the \'prune\' leaf over that entry matches the hand-derived preimage', () => {
    const tree: UtxoTxTree = {
      utxoTxIds: [],
      utxoTxs: [],
      pruneEntries: [asPruneEntry(golden)],
    };
    expect(computeUtxoTxRoot(tree)).toBe(rootOfLeaves(['prune', PRUNE_LEAF_PREIMAGE]));
  });
});

// ---------------------------------------------------------------------------
// The root over a whole body
// ---------------------------------------------------------------------------

const utxoFixture: UtxoTxTree = {
  utxoTxIds: ['ab'.repeat(32), 'cd'.repeat(32)],
  utxoTxs: [], // carried bytes are not part of the root
  pruneEntries: [],
};

describe('Merkle leaf order and composition', () => {
  it('utxoTxRoot leaves are the bare ids, in `utxoTxIds` order', () => {
    expect(computeUtxoTxRoot(utxoFixture)).toBe(
      rootOfLeaves(
        ['utxotx', 'ab'.repeat(32)],
        ['utxotx', 'cd'.repeat(32)],
      ),
    );
  });

  it('leaf ORDER is normative — swapping two ids moves the root', () => {
    const swapped: UtxoTxTree = {
      ...utxoFixture,
      utxoTxIds: ['cd'.repeat(32), 'ab'.repeat(32)],
    };
    expect(computeUtxoTxRoot(swapped)).not.toBe(computeUtxoTxRoot(utxoFixture));
  });

  it('⛔ the settlement contributes ONE leaf and no second class', () => {
    // The substantive property this file exists for after the collapse: the
    // settlement is a transaction, so it appears exactly once, as a `'utxotx'`
    // leaf in last position, and nothing about the coinbase it pays reaches the
    // root separately (TYPES_INTERFACE → Ordering block).
    const settlementId = 'ef'.repeat(32);
    const withSettlement: UtxoTxTree = {
      ...utxoFixture,
      utxoTxIds: [...utxoFixture.utxoTxIds, settlementId],
    };
    expect(computeUtxoTxRoot(withSettlement)).toBe(
      rootOfLeaves(
        ['utxotx', 'ab'.repeat(32)],
        ['utxotx', 'cd'.repeat(32)],
        ['utxotx', settlementId],
      ),
    );
  });

  it('transactions come before prune entries, which is `UtxoTxTree`\'s field order', () => {
    const golden = vector('utxoTxTree/txs-and-prunes');
    const both: UtxoTxTree = {
      utxoTxIds: ['ab'.repeat(32)],
      utxoTxs: [],
      pruneEntries: [asPruneEntry(golden)],
    };
    expect(computeUtxoTxRoot(both)).toBe(
      rootOfLeaves(
        ['utxotx', 'ab'.repeat(32)],
        ['prune', PRUNE_LEAF_PREIMAGE],
      ),
    );
    // …and not the other way round. Reordering is a consensus change with no
    // compiler signal, so it needs an assertion rather than a comment.
    expect(computeUtxoTxRoot(both)).not.toBe(
      rootOfLeaves(
        ['prune', PRUNE_LEAF_PREIMAGE],
        ['utxotx', 'ab'.repeat(32)],
      ),
    );
  });
});
